<Project Sdk="Microsoft.NET.Sdk">

   <PropertyGroup>
	   <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<AssemblyName>MatrixSS</AssemblyName>
		<MyType>None</MyType>
		<OutputType>WinExe</OutputType>
      <StartupObject>Sub Main</StartupObject>
		<TargetFramework>net10.0-windows</TargetFramework>
		<UseWindowsForms>true</UseWindowsForms>
   </PropertyGroup>

   <ItemGroup>
      <Import Include="System.Data" />
      <Import Include="System.Drawing" />
      <Import Include="System.Windows.Forms" />
   </ItemGroup>

	<Target Name="RenameToScr" AfterTargets="Build">
	   <Copy SourceFiles="$(OutputPath)$(AssemblyName).exe" DestinationFiles="$(OutputPath)$(AssemblyName).scr" />
   </Target>
	
</Project>