<Project Sdk="Microsoft.NET.Sdk">

   <PropertyGroup>
	   <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<AssemblyName>MatrixSS</AssemblyName>
		<MyType>None</MyType>
		<OutputType>WinExe</OutputType>
      <StartupObject>Sub Main</StartupObject>
		<TargetFrameworks>net48;net8.0-windows;net10.0-windows</TargetFrameworks>
		<UseWindowsForms>true</UseWindowsForms>
		<Platforms>x64;x86</Platforms>
		<ApplicationIcon>Res\Matrix.ico</ApplicationIcon>
   </PropertyGroup>


   <PropertyGroup Condition="'$(TargetFramework)' != ''">
      <TfmName>$(TargetFramework.Replace('-windows', ''))</TfmName>
      <OutputPath>..\bin\$(Configuration)\$(TfmName) $(Platform)\</OutputPath>
      <IntermediateOutputPath>obj\$(Configuration)\$(TfmName) $(Platform)\</IntermediateOutputPath>
   </PropertyGroup>

   <PropertyGroup Condition="'$(Platform)' == 'x86' Or '$(Platform)' == 'x64'">
      <PlatformTarget>$(Platform)</PlatformTarget>
   </PropertyGroup>

   <ItemGroup>
     <Content Include="Res\Matrix.ico" />
   </ItemGroup>

   <ItemGroup>
      <Import Include="System.Data" />
      <Import Include="System.Drawing" />
      <Import Include="System.Windows.Forms" />
   </ItemGroup>

   <Target Name="RenameToScr" AfterTargets="Build" Condition="'$(TargetFramework)' != ''">
	   <Copy SourceFiles="$(OutputPath)$(AssemblyName).exe" DestinationFiles="$(OutputPath)$(AssemblyName).scr" />
   </Target>
	
</Project>